# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 836)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button1.setGeometry(QtCore.QRect(340, 540, 151, 61))
        self.Button1.setObjectName("Button1")
        self.list1 = QtWidgets.QListWidget(self.centralwidget)
        self.list1.setGeometry(QtCore.QRect(300, 670, 256, 111))
        self.list1.setObjectName("list1")
        self.listaListos = QtWidgets.QListWidget(self.centralwidget)
        self.listaListos.setGeometry(QtCore.QRect(550, 350, 256, 311))
        self.listaListos.setObjectName("listaListos")
        self.processTable = QtWidgets.QTableWidget(self.centralwidget)
        self.processTable.setGeometry(QtCore.QRect(20, 20, 631, 191))
        self.processTable.setObjectName("processTable")
        self.processTable.setColumnCount(5)
        self.processTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.processTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.processTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.processTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.processTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.processTable.setHorizontalHeaderItem(4, item)
        self.ButtonLoadProcess = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonLoadProcess.setGeometry(QtCore.QRect(310, 480, 211, 61))
        self.ButtonLoadProcess.setObjectName("ButtonLoadProcess")
        self.listCPU = QtWidgets.QListWidget(self.centralwidget)
        self.listCPU.setGeometry(QtCore.QRect(320, 350, 201, 61))
        self.listCPU.setObjectName("listCPU")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(370, 310, 121, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.ButtonGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonGenerate.setGeometry(QtCore.QRect(340, 420, 151, 61))
        self.ButtonGenerate.setObjectName("ButtonGenerate")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 310, 261, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.processTable_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.processTable_2.setGeometry(QtCore.QRect(10, 350, 291, 311))
        self.processTable_2.setObjectName("processTable_2")
        self.processTable_2.setColumnCount(5)
        self.processTable_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.processTable_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.processTable_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.processTable_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.processTable_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.processTable_2.setHorizontalHeaderItem(4, item)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(550, 310, 271, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button1.setText(_translate("MainWindow", "Comenzar emulacion"))
        item = self.processTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CPU"))
        item = self.processTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "B.T"))
        item = self.processTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "A.T"))
        item = self.processTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Prioridad"))
        item = self.processTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tiempo restante"))
        self.ButtonLoadProcess.setText(_translate("MainWindow", "Cargar procesos"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">CPU</span></p></body></html>"))
        self.ButtonGenerate.setText(_translate("MainWindow", "Generar procesos"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Procesos listos</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p></body></html>"))
        item = self.processTable_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CPU"))
        item = self.processTable_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "B.T"))
        item = self.processTable_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "A.T"))
        item = self.processTable_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Prioridad"))
        item = self.processTable_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tiempo restante"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Procesos ya ejecutados</span></p></body></html>"))
