# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(908, 678)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button1.setGeometry(QtCore.QRect(230, 220, 93, 28))
        self.Button1.setObjectName("Button1")
        self.list1 = QtWidgets.QListWidget(self.centralwidget)
        self.list1.setGeometry(QtCore.QRect(20, 20, 256, 192))
        self.list1.setObjectName("list1")
        self.list2 = QtWidgets.QListWidget(self.centralwidget)
        self.list2.setGeometry(QtCore.QRect(290, 20, 256, 192))
        self.list2.setObjectName("list2")
        self.processTable = QtWidgets.QTableWidget(self.centralwidget)
        self.processTable.setGeometry(QtCore.QRect(30, 260, 641, 321))
        self.processTable.setObjectName("processTable")
        self.processTable.setColumnCount(5)
        self.processTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.processTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.processTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.processTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.processTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.processTable.setHorizontalHeaderItem(4, item)
        self.ButtonLoadProcess = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonLoadProcess.setGeometry(QtCore.QRect(710, 370, 211, 61))
        self.ButtonLoadProcess.setObjectName("ButtonLoadProcess")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 908, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button1.setText(_translate("MainWindow", "Presionar"))
        item = self.processTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CPU"))
        item = self.processTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "B.T"))
        item = self.processTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "A.T"))
        item = self.processTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Priority"))
        item = self.processTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tiempo restante"))
        self.ButtonLoadProcess.setText(_translate("MainWindow", "Cargar procesos"))
